unit uSQL;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants,
  System.Classes, Vcl.Graphics, IniFiles;

var
  qryBUSCA: String;

implementation

qryBUSCA =
  'SELECT + TMP.IDCODBARPROD | | ';' | | TMP.DESCRICAO | | ';' | |'
  'RIGHT('' | | RTRIM(CAST(CAST(REPLACE(TMP.VALPRECOVAREJO, ',', '') AS BIGINT)'
  'AS CHAR(12))), 12)| | '' / * AS SAIDA * / FROM(SELECT TBL.IDSUBPRODUTO,'
  'TBL.IDCODBARPROD, CAST(SUBSTR(TBL.DESCRICAO, 1, 20) AS VARCHAR(20))'
  'AS DESCRICAO,'
  '(RIGHT('   ' | | RTRIM(CAST(CAST(ROUND((TBL.VALPRECOVAREJO * TBL.QTDMULTIPLA),'
  '2) AS INTEGER) AS CHAR(20)))| | ',' | | RIGHT'
  '(RTRIM(CAST(CAST(ROUND((TBL.VALPRECOVAREJO * TBL.QTDMULTIPLA),'
  '2) AS DECIMAL(15, 2)) AS CHAR(20))), 2), 10)) AS VALPRECOVAREJO FROM'
  '(SELECT PRODUTOS_VIEW.IDSUBPRODUTO,'
  'RIGHT('0000000000000' | | RTRIM'
  '(CAST(CAST(PRODUTOS_VIEW.IDCODBARPROD AS BIGINT) AS CHAR(20))),'
  '13) AS IDCODBARPROD, CAST(SUBSTR(PRODUTOS_VIEW.DESCRICAOPRODUTO, 1,'
  '20) AS VARCHAR(20)) AS DESCRICAO,'
  'CAST(COALESCE(UF_GETMENORPRECOVENDA(POLITICA_PRECO_PRODUTO.IDEMPRESA,'
  'CAST(NULL AS INTEGER), PRODUTOS_VIEW.IDPRODUTO, PRODUTOS_VIEW.IDSUBPRODUTO,'
  'CAST('V' AS CHAR(1))), 2) AS NUMERIC(15, 2)) AS VALPRECOVAREJO,'
  'CAST(PRODUTOS_VIEW.VALMULTIVENDAS AS DECIMAL(15, 6))'
  'AS QTDMULTIPLA FROM EMPRESA, POLITICA_PRECO_PRODUTO, PRODUTOS_VIEW,'
  'PRODUTO WHERE PRODUTO.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO AND'
  'POLITICA_PRECO_PRODUTO.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO AND '
  'POLITICA_PRECO_PRODUTO.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO AND'
  'EMPRESA.IDEMPRESA = POLITICA_PRECO_PRODUTO.IDEMPRESA AND'
  'POLITICA_PRECO_PRODUTO.IDEMPRESA = 7 AND PRODUTOS_VIEW.FLAGINATIVO = ''F''' AND
  'PRODUTOS_VIEW.FLAGEXPBALANCA = ''''F'''''

  'UNION'

  'SELECT PRODUTOS_VIEW.IDSUBPRODUTO,'
  'RIGHT('0000000000000' | | RTRIM(CAST(CAST(TB_COD_BAR_CX.CODBARCX AS BIGINT)
  'AS CHAR(20))), 13) AS IDCODBARPROD,
  'CAST(SUBSTR(PRODUTOS_VIEW.DESCRICAOPRODUTO, 1, 45)| | ' [CX]' AS VARCHAR(50))
  'AS DESCRICAO, CAST(COALESCE(UF_GETMENORPRECOVENDA
  '(POLITICA_PRECO_PRODUTO.IDEMPRESA, CAST(NULL AS INTEGER),
  'PRODUTOS_VIEW.IDPRODUTO, PRODUTOS_VIEW.IDSUBPRODUTO, CAST('V' AS CHAR(1))),
  '2) AS NUMERIC(15, 2)) AS VALPRECOVAREJO,
  'TB_COD_BAR_CX.QTDMULTIPLA FROM EMPRESA, POLITICA_PRECO_PRODUTO, PRODUTO,
  'PRODUTOS_VIEW JOIN(SELECT Q2.IDPRODUTO, Q2.IDSUBPRODUTO, Q2.QTDMULTIPLA,
  'Q2.CODBARCX FROM(SELECT Q1.IDPRODUTO, Q1.IDSUBPRODUTO, Q1.QTDMULTIPLA,
  'Q1.CODBARCX, (ROW_NUMBER()OVER(PARTITION BY Q1.IDPRODUTO,
  'Q1.IDSUBPRODUTO ORDER BY(CASE WHEN QTDMULTIPLA IS NULL THEN 0 ELSE 1 END)DESC,
  'Q1.CONSULTA ASC)) AS RANK1 FROM(SELECT '1' AS CONSULTA, CODCX.IDPRODUTO,
  'CODCX.IDSUBPRODUTO, CODCX.QTDMULTIPLA,
  'CODCX.CODBARCX AS CODBARCX FROM PRODUTO_GRADE_CODBARCX AS CODCX JOIN
  '(SELECT ROW_NUMBER()OVER(PARTITION BY CODCX.IDPRODUTO,
  'CODCX.IDSUBPRODUTO ORDER BY CODCX.DTALTERACAO DESC) AS LINHA, CODCX.IDPRODUTO,
  'CODCX.IDSUBPRODUTO, CODCX.CODBARCX,
  'CODCX.DTALTERACAO FROM PRODUTO_GRADE_CODBARCX AS CODCX JOIN PRODUTO ON
  '(PRODUTO.IDPRODUTO = CODCX.IDPRODUTO)WHERE CODCX.QTDMULTIPLA = PRODUTO.
  'VALGRAMAENTRADA) AS Q1 ON(Q1.IDPRODUTO = CODCX.IDPRODUTO AND
  'Q1.IDSUBPRODUTO = CODCX.IDSUBPRODUTO AND Q1.CODBARCX = CODCX.CODBARCX / * AND
  'Q1.LINHA = 1 * / )

  'UNION ALL

  'SELECT '2' AS CONSULTA, CODCX.IDPRODUTO, CODCX.IDSUBPRODUTO,
  'CODCX.QTDMULTIPLA, CODCX.CODBARCX FROM PRODUTO_GRADE_CODBARCX AS CODCX JOIN
  '(SELECT ROW_NUMBER()OVER(PARTITION BY CODCX.IDPRODUTO,
  'CODCX.IDSUBPRODUTO ORDER BY CODCX.DTALTERACAO DESC) AS LINHA, CODCX.IDPRODUTO,
  'CODCX.IDSUBPRODUTO, CODCX.CODBARCX,
  'CODCX.DTALTERACAO FROM PRODUTO_GRADE_CODBARCX AS CODCX JOIN PRODUTO ON
  '(PRODUTO.IDPRODUTO = CODCX.IDPRODUTO)WHERE CODCX.QTDMULTIPLA <>
  'PRODUTO.VALGRAMAENTRADA) AS Q1 ON(Q1.IDPRODUTO = CODCX.IDPRODUTO AND
  'Q1.IDSUBPRODUTO = CODCX.IDSUBPRODUTO AND Q1.CODBARCX = CODCX.CODBARCX / * AND
  'Q1.LINHA = 1 * / )) AS Q1) AS Q2 / * WHERE RANK1 = 1 * / )
  'AS TB_COD_BAR_CX ON(TB_COD_BAR_CX.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO AND
  'TB_COD_BAR_CX.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO AND
  'TB_COD_BAR_CX.QTDMULTIPLA = PRODUTOS_VIEW.VALGRAMAENTRADA)
  'WHERE PRODUTO.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO AND
  'POLITICA_PRECO_PRODUTO.IDPRODUTO = PRODUTOS_VIEW.IDPRODUTO AND
  'POLITICA_PRECO_PRODUTO.IDSUBPRODUTO = PRODUTOS_VIEW.IDSUBPRODUTO AND
  'EMPRESA.IDEMPRESA = POLITICA_PRECO_PRODUTO.IDEMPRESA AND
  'POLITICA_PRECO_PRODUTO.IDEMPRESA = 7 AND PRODUTOS_VIEW.FLAGINATIVO = 'F' AND
  'PRODUTOS_VIEW.FLAGEXPBALANCA = 'F') AS TBL WHERE TBL.VALPRECOVAREJO >'
  '0) AS TMP';

end.
